### ISSUE TITLE
NullPointerException at org.apache.catalina.connector.Response.sendRedirect

### ISSUE THREAD

**Issue by jzuijlek** [viviotech/mod_cfml#27]
The first redirect after creating a new contexts results in this error:

> 31-Jul-2019 21:07:06.082 INFO [fe-api.dev-startStop-1] org.apache.catalina.startup.HostConfig.deployDescriptor Deployment of configuration descriptor [/etc/tomcat8/Catalina/fe-api.dev/ROOT.xml] has finished in [90] ms
[mod_cfml][1] Verifying context files...
[mod_cfml][1] Redirect URL => '/index.cfm?'
31-Jul-2019 21:07:06.084 SEVERE [http-nio-8888-exec-4] org.apache.coyote.http11.Http11Processor.service Error processing request
 java.lang.NullPointerException
	at org.apache.catalina.connector.Response.sendRedirect(Response.java:1330)
	at org.apache.catalina.connector.Response.sendRedirect(Response.java:1299)
	at mod_cfml.core.doRedirect(core.java:530)
	at mod_cfml.core.invoke(core.java:515)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:679)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by utdream** [comment]
Hi jzuijlek,

Can you provide us with the full URL you were using? You can anonymize it if necessary. It would also be helpful to know what web server you were using.

Thank you!

-Jordan

**Comment by jzuijlek** [comment]
Url is http://fe-api.dev.

Using nginx with this config: https://github.com/foundeo/ubuntu-nginx-lucee/tree/master/etc/nginx

Full log from the start of the first request:

> [mod_cfml][2] Decoded Request URI => /index.cfm
[mod_cfml][2] QueryString => null
[mod_cfml][2] DocRoot Value => /var/www/fe-api.dev
[mod_cfml][2] Host Value => fe-api.dev
[mod_cfml][2] Removing old config directory: /etc/tomcat8/Catalina/fe-api.dev
[mod_cfml][2] Creating new config directory: /etc/tomcat8/Catalina/fe-api.dev
[mod_cfml][2] Removing old work directory: /var/cache/tomcat8/Catalina/fe-api.dev
[mod_cfml][2] Creating New Host... 
[mod_cfml][2] setName Value => fe-api.dev
01-Aug-2019 07:57:05.817 INFO [fe-api.dev-startStop-1] org.apache.catalina.startup.HostConfig.deployDescriptor Deploying configuration descriptor [/etc/tomcat8/Catalina/fe-api.dev/ROOT.xml]
01-Aug-2019 07:57:05.941 INFO [fe-api.dev-startStop-1] org.apache.catalina.startup.HostConfig.deployDescriptor Deployment of configuration descriptor [/etc/tomcat8/Catalina/fe-api.dev/ROOT.xml] has finished in [124] ms
[mod_cfml][2] Verifying context files...
[mod_cfml][2] Redirect URL => '/index.cfm?'
01-Aug-2019 07:57:05.943 SEVERE [http-nio-8888-exec-6] org.apache.coyote.http11.Http11Processor.service Error processing request
 java.lang.NullPointerException
	at org.apache.catalina.connector.Response.sendRedirect(Response.java:1330)
	at org.apache.catalina.connector.Response.sendRedirect(Response.java:1299)
	at mod_cfml.core.doRedirect(core.java:530)
	at mod_cfml.core.invoke(core.java:515)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:679)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by jzuijlek** [comment]
Upon investigating further, I stumbled on this: https://luceeserver.atlassian.net/browse/LDEV-2215

When using OpenJDK 8 instead of OpenJDK 11, the above error is gone and I get a normal 302 redirect.

**Comment by utdream** [comment]
thanks @jzuijlek
